server:
  port: 7000
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xpp1109/spring-cloud-v202003.git
          basedir: config-repo
          password:
          username:
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://xpp:xpp@localhost:8761/eureka}"