server:
  port: 7000
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
eureka:
  client:
    service-url:
      defaultZone: "${DISCOVERY_URL:http://xpp:xpp@localhost:8761/eureka}"